CREATE TABLE NHANVIEN
(
	MANV 	CHAR(4) PRIMARY KEY,
	HOTEN	VARCHAR(40),
	EMAIL	VARCHAR(50),
	SODT	VARCHAR(20),
	NGSINH	SMALLDATETIME,
	LVL		SMALLINT,
	MACM	CHAR(4),
	GHICHU	VARCHAR(80),
);
CREATE TABLE CHUYENMON
(
	MACM	CHAR(4) PRIMARY KEY,
	TENCM	VARCHAR(15),
);
CREATE TABLE TAIKHOAN
(
	MATK	CHAR(4) PRIMARY KEY,
	MANV	CHAR(4),
	MAQH	CHAR(4),
	EMAIL	VARCHAR(50),
	PASS	VARCHAR(20),
);
CREATE TABLE QUYENHAN
(
	MAQH	CHAR(4) PRIMARY KEY,
	TENQH	VARCHAR(15),
);
CREATE TABLE LOAISK
(
	MALSK	CHAR(4) PRIMARY KEY,
	TENLSK	VARCHAR(20),
	MONEYMIN	MONEY,
	MONEYMAX	MONEY,
);
CREATE TABLE DUAN
(
	MADA	CHAR(4) PRIMARY KEY,
	MALSK	CHAR(4),
	MAOWNER	CHAR(4),
	TENDA	VARCHAR(80),
	NGANSACH	MONEY,
	TSTART	SMALLDATETIME,
	TEND	SMALLDATETIME,
	STAT	VARCHAR(15),

);
CREATE TABLE CONGVIEC
(
	MACV	CHAR(4) PRIMARY KEY,
	MADA	CHAR(4),
	MANV	CHAR(4),
	MACM	CHAR(4),
	TENCV	VARCHAR (80),
	TSTART	SMALLDATETIME,
	TEND	SMALLDATETIME,
	NGANSACH	MONEY,
	DADUNG	MONEY,
	TIENDO	SMALLINT,
	YCDINHKEM	VARCHAR(20),
	TEPDINHKEM	VARCHAR(50),
);
