CREATE TABLE NHANVIEN
(
	MANV 	CHAR(4) PRIMARY KEY,
	HOTEN	VARCHAR(40),
	EMAIL	VARCHAR(50),
	SODT	VARCHAR(20),
	NGSINH	SMALLDATETIME,
	LVL		SMALLINT,
	MACM	CHAR(4),
	GHICHU	VARCHAR(80),
);
CREATE TABLE CHUYENMON
(
	MACM	CHAR(4) PRIMARY KEY,
	TENCM	VARCHAR(15),
);
CREATE TABLE TAIKHOAN
(
	MATK	CHAR(4) PRIMARY KEY,
	MANV	CHAR(4),
	MAQH	CHAR(4),
	EMAIL	VARCHAR(50),
	PASS	VARCHAR(20),
);
CREATE TABLE QUYENHAN
(
	MAQH	CHAR(4) PRIMARY KEY,
	TENQH	VARCHAR(15),
);
CREATE TABLE LOAISK
(
	MALSK	CHAR(4) PRIMARY KEY,
	TENLSK	VARCHAR(20),
	MONEYMIN	MONEY,
	MONEYMAX	MONEY,
);
CREATE TABLE DUAN
(
	MADA	CHAR(4) PRIMARY KEY,
	MALSK	CHAR(4),
	MAOWNER	CHAR(4),
	TENDA	VARCHAR(80),
	NGANSACH	MONEY,
	TSTART	SMALLDATETIME,
	TEND	SMALLDATETIME,
	STAT	VARCHAR(15),

);
CREATE TABLE CONGVIEC
(
	MACV	CHAR(4) PRIMARY KEY,
	MADA	CHAR(4),
	MANV	CHAR(4),
	MACM	CHAR(4),
	TENCV	VARCHAR (80),
	TSTART	SMALLDATETIME,
	TEND	SMALLDATETIME,
	NGANSACH	MONEY,
	DADUNG	MONEY,
	TIENDO	SMALLINT,
	YCDINHKEM	VARCHAR(20),
	TEPDINHKEM	VARCHAR(50),
);
--------------------------------------------------------------------------------
--TẠO TRIGGER CHO ĐIỀU KIỆN NGÂN SÁCH
CREATE OR ALTER TRIGGER Check_NGANSACH
ON DUAN
AFTER INSERT, UPDATE
AS
BEGIN
    -- Khai báo các biến
    DECLARE @MALSK CHAR(10);
    DECLARE @MONEYMIN INT;
    DECLARE @MONEYMAX INT;
    DECLARE @TENLSK NVARCHAR(100);

    -- Lặp qua các hàng được chèn hoặc cập nhật
    DECLARE cur CURSOR FOR
    SELECT i.MALSK
    FROM inserted i;

    OPEN cur;
    FETCH NEXT FROM cur INTO @MALSK;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- Lấy giá trị MONEYMIN, MONEYMAX và TENLSK từ bảng LOAISK tương ứng với MALSK
        SELECT @MONEYMIN = MONEYMIN, @MONEYMAX = MONEYMAX, @TENLSK = TENLSK
        FROM LOAISK
        WHERE MALSK = @MALSK;

        -- Kiểm tra điều kiện và nếu không thỏa mãn, phát sinh lỗi
        IF EXISTS (
            SELECT 1
            FROM inserted i
            WHERE i.NGANSACH > @MONEYMAX OR i.NGANSACH < @MONEYMIN
        )
        BEGIN
            DECLARE @ErrorMessage NVARCHAR(100);
            SET @ErrorMessage = N'Ngân sách phải nằm trong khoảng ' + CAST(@MONEYMIN AS NVARCHAR(10)) + N' và ' + CAST(@MONEYMAX AS NVARCHAR(10)) + N' cho sự kiện ' + @TENLSK;
            RAISERROR(@ErrorMessage, 16, 1);
            ROLLBACK TRANSACTION;
            CLOSE cur;
            DEALLOCATE cur;
            RETURN;
        END;

        FETCH NEXT FROM cur INTO @MALSK;
    END;

    CLOSE cur;
    DEALLOCATE cur;
END;
----------------------------------------------------------------------------
